/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1990_tv.glb 
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1990-tv-f4a523c95d964e1c973856c9b2bca233
Title: 1990 TV
*/
"use client";

import React, { useEffect, useRef } from "react";
import { useAnimations, useGLTF, useVideoTexture } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from 'gsap';
import * as THREE from 'three';

export default function DemoComputer(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/1990_tv.glb');
  const { actions } = useAnimations(animations, group);

  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4');

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txt]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.238}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.DefaultMaterial}
            
          >
            <meshBasicMaterial map={txt}  />
          </mesh> 
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.DefaultMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/1990_tv.glb");