// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Shuffling.GLB 
*/


import React from "react";
import { useGLTF } from "@react-three/drei";


export function Model3(props) {
  const { nodes, materials } = useGLTF("/Shuffling.GLB");
  return (
    <group {...props} dispose={null}>
      <lineSegments
        
        geometry={nodes.mesh.geometry}
        material={materials.material1}
      />
    </group>
  );
}

useGLTF.preload("/Shuffling.GLB");
